services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    develop:
      watch:
        - action: rebuild
          path: ./Dockerfile
        - action: rebuild
          path: ./requirements.txt
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  react:
    image: node:24.12.0-alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
    command: sh -c "corepack enable && corepack prepare yarn@4.13.0 --activate && yarn install && yarn dev --host"
    restart: unless-stopped
