[pytest]
minversion = 8.0
DJANGO_SETTINGS_MODULE = project.settings.dev
python_files = tests.py test_*.py *_tests.py
;asyncio_mode = auto
;asyncio_default_fixture_loop_scope = function
testpaths = insights/tests
filterwarnings =
    ignore::pytest.PytestConfigWarning
;    ignore::DeprecationWarning
;    ignore:asyncio_mode
markers =
    focus: Generic focus
    dev: For one-shots
