# Generated by Django 5.2.9 on 2026-01-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Macro", "Macro"),
                            ("Equities", "Equities"),
                            ("FixedIncome", "Fixed Income"),
                            ("Alternatives", "Alternatives"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                ("tags", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category"], name="insights_in_categor_05abe2_idx"
                    )
                ],
            },
        ),
    ]
