# Generated by Django 6.0.4 on 2026-04-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="insight",
            name="insights_in_categor_05abe2_idx",
        ),
        migrations.AddField(
            model_name="insight",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="insight",
            name="category",
            field=models.CharField(
                choices=[
                    ("Macro", "Macro"),
                    ("Equities", "Equities"),
                    ("FixedIncome", "Fixed Income"),
                    ("Alternatives", "Alternatives"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=["deleted_at"],
                name="idx_insight_delat",
            ),
        ),
    ]
