# Generated by Django 6.0.4 on 2026-04-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0003_insight_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="category",
            field=models.CharField(
                choices=[
                    ("Macro", "macro"),
                    ("Equities", "equities"),
                    ("FixedIncome", "fixed income"),
                    ("Alternatives", "alternatives"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
