# Generated by Django 6.0.4 on 2026-04-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0004_alter_insight_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insight",
            name="category",
            field=models.CharField(
                choices=[
                    ("macro", "Macro"),
                    ("equities", "Equities"),
                    ("fixedincome", "Fixed Income"),
                    ("alternatives", "Alternatives"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
